### ISSUE TITLE
Why do you put your "imports on separate lines each at bottom" ?

### ISSUE THREAD

**Issue by correabuscar** [SabrinaJewson/SabrinaJewson#1]
In https://sabrinajewson.org/blog/errors
you said:
> You might have noticed I put my imports on separate lines each at bottom — I do have my reasons for this, but that’s best saved for another day ;)

I've searched but haven't found anything about this yet.

Would you please state why you're placing imports at the bottom?

**Comment by SabrinaJewson** [comment]
Good question!

My reasoning for putting imports at the end is to follow the general consistent philosophy of “important stuff at the top, unimportant stuff at the bottom”: that is, when I open a file I want to first of all see the main thing the file does, keeping irrelevant helpers and utilities as low down as possible. So, if you have a file like this:

```rs
use some::function;

pub fn the_main_function() { /* business logic */ }

fn utility_function() {}
```

I find it inconsistent that the “reading order” goes `the_main_function` → `utility_function` → `use`, and putting imports at the bottom rectifies this. It would also be consistent to put imports at the top, then utility code, then main logic, more common in “single-pass” languages like C (which is why it makes sense to have `#include`s at the top in such languages), but I think since Rust can work with things in reverse order, it is overall more readable to use this style. I don’t feel incredibly strongly about this – I don’t mind working with other styles at all – it’s just something nice I like to use in my own code
